# Generated by Django 4.2.4 on 2024-10-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='paystack_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topuprequest',
            name='payment_channel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admininfo',
            name='ishare_channel',
            field=models.CharField(blank=True, choices=[('Gyasi', 'Gyasi')], default='Gyasi', max_length=250, null=True),
        ),
    ]
