# Generated by Django 4.2.4 on 2024-10-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0004_wallettransaction_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topuprequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=100),
        ),
    ]
