# Generated by Django 4.2.4 on 2024-11-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0005_alter_topuprequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigtimetransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='isharebundletransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='mtntransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='teleceltransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
